{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nexus.fullname" . }}-api-pdb
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" (dict "context" . "component" "api") | nindent 6 }}
---
{{- end }}
{{- if .Values.frontend.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nexus.fullname" . }}-frontend-pdb
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" (dict "context" . "component" "frontend") | nindent 6 }}
{{- end }}
