apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus.fullname" . }}-scheduler
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" (dict "context" . "component" "scheduler") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus.labels" . | nindent 8 }}
        {{- include "nexus.selectorLabels" (dict "context" . "component" "scheduler") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "nexus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: scheduler
          image: "{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
          command: {{ .Values.scheduler.command | toJson }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "nexus.fullname" . }}-config
            - secretRef:
                name: {{ include "nexus.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
