apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus.fullname" . }}-worker
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" (dict "context" . "component" "worker") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus.labels" . | nindent 8 }}
        {{- include "nexus.selectorLabels" (dict "context" . "component" "worker") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "nexus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: {{ .Values.worker.command | toJson }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "nexus.fullname" . }}-config
            - secretRef:
                name: {{ include "nexus.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
