"""obsidian_documents, and a polymorphic parent for knowledge_chunks

ADR 0002 §17. The vault owns note bodies; obsidian_documents owns their identity
and index state so a human moving or renaming a file is detected as a move
rather than a new document plus an orphaned row.

knowledge_chunks.page_id gains a second possible parent (an obsidian_documents
row instead of a knowledge_pages row), so its single-target foreign key is
dropped. The column and its index stay: only the database-level constraint is
relaxed, because no single FK can point at two tables.

Revision ID: c2f9a4d81b70
Revises: b6f3d1a72e60
Create Date: 2026-08-29
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = "c2f9a4d81b70"
down_revision: Union[str, None] = "b6f3d1a72e60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Auto-generated by PostgreSQL for the unnamed constraint in the initial schema.
_CHUNK_PAGE_FK = "knowledge_chunks_page_id_fkey"


def upgrade() -> None:
    op.create_table(
        "obsidian_documents",
        sa.Column("nexus_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("vault_path", sa.String(length=1024), nullable=False),
        sa.Column("doc_type", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("mtime", sa.DateTime(), nullable=False),
        sa.Column("index_status", sa.String(length=20), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.Column("embedding_dimension", sa.Integer(), nullable=True),
        sa.Column("indexed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"]),
        sa.PrimaryKeyConstraint("nexus_id"),
    )
    op.create_index(
        "ix_obsidian_documents_company_id", "obsidian_documents", ["company_id"]
    )
    op.create_index(
        "ix_obsidian_documents_vault_path", "obsidian_documents", ["vault_path"]
    )
    op.create_index(
        "ix_obsidian_documents_doc_type", "obsidian_documents", ["doc_type"]
    )
    op.create_index(
        "ix_obsidian_documents_index_status", "obsidian_documents", ["index_status"]
    )
    # One path per company: a duplicate row for the same file would index the
    # same body twice and make change detection ambiguous.
    op.create_index(
        "uq_obsidian_documents_company_path",
        "obsidian_documents",
        ["company_id", "vault_path"],
        unique=True,
    )

    if op.get_bind().dialect.name == "postgresql":
        op.drop_constraint(_CHUNK_PAGE_FK, "knowledge_chunks", type_="foreignkey")


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        # Only restorable while no chunk points at an obsidian_documents row.
        op.create_foreign_key(
            _CHUNK_PAGE_FK,
            "knowledge_chunks",
            "knowledge_pages",
            ["page_id"],
            ["id"],
        )

    op.drop_index(
        "uq_obsidian_documents_company_path", table_name="obsidian_documents"
    )
    op.drop_index(
        "ix_obsidian_documents_index_status", table_name="obsidian_documents"
    )
    op.drop_index("ix_obsidian_documents_doc_type", table_name="obsidian_documents")
    op.drop_index("ix_obsidian_documents_vault_path", table_name="obsidian_documents")
    op.drop_index("ix_obsidian_documents_company_id", table_name="obsidian_documents")
    op.drop_table("obsidian_documents")
