"""add kill_switch_records table

Revision ID: ca7238bc6797
Revises: db96cb66effc
Create Date: 2026-08-19 01:34:34.355385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca7238bc6797'
down_revision: Union[str, None] = 'db96cb66effc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kill_switch_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.Column('activated_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kill_switch_records_company_id'), 'kill_switch_records', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kill_switch_records_company_id'), table_name='kill_switch_records')
    op.drop_table('kill_switch_records')
    # ### end Alembic commands ###
