"""add notifications pipelines repos settings

Revision ID: cb75b52327c0
Revises: a1b2c3d4e5f6
Create Date: 2026-08-22 20:55:21.159718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb75b52327c0'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_checkpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_checkpoints_task_id'), 'execution_checkpoints', ['task_id'], unique=False)
    op.create_table('company_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('workspace_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('default_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('default_adapter', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('default_budget_cents', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('heartbeat_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('auto_pause_idle', sa.Boolean(), nullable=False),
    sa.Column('evolution_enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('circuit_breaker_threshold', sa.Integer(), nullable=False),
    sa.Column('require_approval_high_risk', sa.Boolean(), nullable=False),
    sa.Column('audit_logging_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_assign_tasks', sa.Boolean(), nullable=False),
    sa.Column('daily_standup_enabled', sa.Boolean(), nullable=False),
    sa.Column('standup_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('sprint_duration_days', sa.Integer(), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_settings_company_id'), 'company_settings', ['company_id'], unique=True)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('slack_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_start', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('quiet_end', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('agent_completions', sa.Boolean(), nullable=False),
    sa.Column('pipeline_failures', sa.Boolean(), nullable=False),
    sa.Column('security_alerts', sa.Boolean(), nullable=False),
    sa.Column('system_updates', sa.Boolean(), nullable=False),
    sa.Column('mentions', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_company_id'), 'notification_preferences', ['company_id'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stages', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_company_id'), 'pipelines', ['company_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_company_id'), 'repositories', ['company_id'], unique=False)
    op.create_table('tool_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('transport_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('endpoint_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('auth_kind', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('credential_ref', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('health_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_health_check_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_connections_company_id'), 'tool_connections', ['company_id'], unique=False)
    op.create_table('tool_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('effect', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_policies_company_id'), 'tool_policies', ['company_id'], unique=False)
    op.create_table('tool_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_profiles_company_id'), 'tool_profiles', ['company_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_company_id'), 'pipeline_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_pipeline_id'), 'pipeline_runs', ['pipeline_id'], unique=False)
    op.create_table('tool_catalog_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['tool_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_catalog_entries_company_id'), 'tool_catalog_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_tool_catalog_entries_connection_id'), 'tool_catalog_entries', ['connection_id'], unique=False)
    op.create_table('tool_profile_bindings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['tool_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_profile_bindings_company_id'), 'tool_profile_bindings', ['company_id'], unique=False)
    op.create_index(op.f('ix_tool_profile_bindings_profile_id'), 'tool_profile_bindings', ['profile_id'], unique=False)
    op.create_index(op.f('ix_tool_profile_bindings_target_id'), 'tool_profile_bindings', ['target_id'], unique=False)
    op.create_table('heartbeat_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('session_id_before', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_id_after', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('process_pid', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('signal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stdout_excerpt', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('stderr_excerpt', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('liveness_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('continuation_attempt', sa.Integer(), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('invocation_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_output_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeat_runs_agent_id'), 'heartbeat_runs', ['agent_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notification_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('notification_metadata', sa.JSON(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_agent_id'), 'notifications', ['agent_id'], unique=False)
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('arguments_scrubbed', sa.JSON(), nullable=True),
    sa.Column('result_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('approval_state', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_invocations_agent_id'), 'tool_invocations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tool_invocations_company_id'), 'tool_invocations', ['company_id'], unique=False)
    op.create_index(op.f('ix_tool_invocations_tool_id'), 'tool_invocations', ['tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_invocations_tool_id'), table_name='tool_invocations')
    op.drop_index(op.f('ix_tool_invocations_company_id'), table_name='tool_invocations')
    op.drop_index(op.f('ix_tool_invocations_agent_id'), table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_agent_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_heartbeat_runs_agent_id'), table_name='heartbeat_runs')
    op.drop_table('heartbeat_runs')
    op.drop_index(op.f('ix_tool_profile_bindings_target_id'), table_name='tool_profile_bindings')
    op.drop_index(op.f('ix_tool_profile_bindings_profile_id'), table_name='tool_profile_bindings')
    op.drop_index(op.f('ix_tool_profile_bindings_company_id'), table_name='tool_profile_bindings')
    op.drop_table('tool_profile_bindings')
    op.drop_index(op.f('ix_tool_catalog_entries_connection_id'), table_name='tool_catalog_entries')
    op.drop_index(op.f('ix_tool_catalog_entries_company_id'), table_name='tool_catalog_entries')
    op.drop_table('tool_catalog_entries')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_company_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_tool_profiles_company_id'), table_name='tool_profiles')
    op.drop_table('tool_profiles')
    op.drop_index(op.f('ix_tool_policies_company_id'), table_name='tool_policies')
    op.drop_table('tool_policies')
    op.drop_index(op.f('ix_tool_connections_company_id'), table_name='tool_connections')
    op.drop_table('tool_connections')
    op.drop_index(op.f('ix_repositories_company_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_pipelines_company_id'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_notification_preferences_company_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_company_settings_company_id'), table_name='company_settings')
    op.drop_table('company_settings')
    op.drop_index(op.f('ix_execution_checkpoints_task_id'), table_name='execution_checkpoints')
    op.drop_table('execution_checkpoints')
    # ### end Alembic commands ###
