import type { Agent2D } from './types';

export const INITIAL_AGENTS_2D: Agent2D[] = [
  // 1. Architect (Executive Manager)
  {
    id: 'agent-manager',
    name: 'Architect',
    role: 'Engineering Manager & Strategist',
    model: 'GPT-4o',
    zoneId: 'executive',
    deskId: 'manager-desk',
    status: 'working',
    state2D: 'working_at_desk',
    x: 205,
    y: 86,
    targetX: 205,
    targetY: 86,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 1.6,
    nextRoamDecisionTime: Date.now() + 8000,
    currentActionDuration: 12000,
    actionStartTime: Date.now(),
    currentTask: 'Delegating Sprint 14 architecture tasks to team',
    taskProgress: 68,
    capabilities: ['Architecture', 'System Design', 'Code Review', 'Strategy'],
    cpu: 62,
    memory: 54,
    tokensUsed: 142000,
    energy: 95,
    sparklineData: [50, 55, 58, 60, 62, 60, 61, 62],
    sprite: {
      hairColor: '#D1D5DB', // Silver/Grey
      hairStyle: 'short',
      skinTone: '#FCD34D',
      outfitColor: '#1E293B', // Charcoal suit
      pantsColor: '#0F172A',
      accessory: 'glasses',
      accessoryColor: '#F59E0B',
      auraColor: '#FFB020',
    },
    bubble: {
      text: 'Reviewing quarterly architecture roadmap...',
      emoji: '📐',
      expiresAt: Date.now() + 6000,
      type: 'thought',
    },
  },

  // 2. Alpha (Backend Dev Lead)
  {
    id: 'agent-001',
    name: 'Alpha',
    role: 'Backend Dev Lead',
    model: 'GPT-4o',
    zoneId: 'development',
    deskId: 'dev-d1',
    status: 'working',
    state2D: 'working_at_desk',
    x: 128,
    y: 378,
    targetX: 128,
    targetY: 378,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 1.8,
    nextRoamDecisionTime: Date.now() + 14000,
    currentActionDuration: 18000,
    actionStartTime: Date.now(),
    currentTask: 'Building REST API & GraphQL federated schema',
    taskProgress: 78,
    capabilities: ['API Design', 'Database', 'Microservices', 'Node.js'],
    cpu: 74,
    memory: 66,
    tokensUsed: 198000,
    energy: 88,
    sparklineData: [45, 52, 48, 61, 72, 68, 75, 72],
    sprite: {
      hairColor: '#1E293B', // Dark hair
      hairStyle: 'messy',
      skinTone: '#FBBF24',
      outfitColor: '#2563EB', // Blue hoodie
      pantsColor: '#1E293B',
      accessory: 'headphones',
      accessoryColor: '#38BDF8',
      auraColor: '#3B82F6',
    },
    bubble: null,
  },

  // 3. Beta (Frontend Dev Lead)
  {
    id: 'agent-002',
    name: 'Beta',
    role: 'Frontend Dev Lead',
    model: 'Claude 3.5 Sonnet',
    zoneId: 'development',
    deskId: 'dev-d2',
    status: 'working',
    state2D: 'working_at_desk',
    x: 268,
    y: 378,
    targetX: 268,
    targetY: 378,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 1.7,
    nextRoamDecisionTime: Date.now() + 10000,
    currentActionDuration: 15000,
    actionStartTime: Date.now(),
    currentTask: 'Polishing 2D OpenOffice pixel canvas animations',
    taskProgress: 92,
    capabilities: ['React', 'TypeScript', 'Tailwind', 'Canvas 2D', 'UI/UX'],
    cpu: 58,
    memory: 45,
    tokensUsed: 165000,
    energy: 92,
    sparklineData: [30, 42, 55, 48, 52, 58, 54, 58],
    sprite: {
      hairColor: '#F472B6', // Pink hair
      hairStyle: 'ponytail',
      skinTone: '#FDE047',
      outfitColor: '#0D9488', // Teal jacket
      pantsColor: '#134E4A',
      accessory: 'visor',
      accessoryColor: '#2DD4BF',
      auraColor: '#06B6D4',
    },
    bubble: null,
  },

  // 4. Gamma (QA & Security Auditor)
  {
    id: 'agent-003',
    name: 'Gamma',
    role: 'QA & Regression Lead',
    model: 'Gemini 1.5 Pro',
    zoneId: 'qa-security',
    deskId: 'qa-d1',
    status: 'review',
    state2D: 'idle_roaming',
    x: 1008,
    y: 378,
    targetX: 1008,
    targetY: 378,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 1.7,
    nextRoamDecisionTime: Date.now() + 3000,
    currentActionDuration: 6000,
    actionStartTime: Date.now(),
    currentTask: 'Verifying security audit on pull request #142',
    taskProgress: 92,
    capabilities: ['Testing', 'Security Audit', 'Fuzzing', 'CI/CD'],
    cpu: 34,
    memory: 28,
    tokensUsed: 89000,
    energy: 82,
    sparklineData: [20, 25, 34, 30, 28, 34, 32, 34],
    sprite: {
      hairColor: '#E2E8F0', // Platinum
      hairStyle: 'spiky',
      skinTone: '#FDE047',
      outfitColor: '#D97706', // Amber armor
      pantsColor: '#78350F',
      accessory: 'armor',
      accessoryColor: '#F59E0B',
      auraColor: '#F59E0B',
    },
    bubble: {
      text: 'Zero memory leaks detected so far.',
      emoji: '🛡️',
      expiresAt: Date.now() + 5000,
      type: 'thought',
    },
  },

  // 5. Delta (DevOps & Deploy)
  {
    id: 'agent-004',
    name: 'Delta',
    role: 'DevOps & Infra Engineer',
    model: 'GPT-4o',
    zoneId: 'operations',
    deskId: 'ops-d1',
    status: 'working',
    state2D: 'working_at_desk',
    x: 578,
    y: 718,
    targetX: 578,
    targetY: 718,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 1.9,
    nextRoamDecisionTime: Date.now() + 16000,
    currentActionDuration: 20000,
    actionStartTime: Date.now(),
    currentTask: 'Deploying Kubernetes v2.4 rollout cluster',
    taskProgress: 60,
    capabilities: ['Docker', 'Kubernetes', 'GCP', 'Terraform', 'CI/CD'],
    cpu: 85,
    memory: 72,
    tokensUsed: 220000,
    energy: 78,
    sparklineData: [65, 70, 78, 82, 85, 80, 83, 85],
    sprite: {
      hairColor: '#9A3412', // Auburn
      hairStyle: 'short',
      skinTone: '#FBBF24',
      outfitColor: '#EA580C', // Orange utility vest
      pantsColor: '#431407',
      accessory: 'headband',
      accessoryColor: '#FDBA74',
      auraColor: '#EA580C',
    },
    bubble: null,
  },

  // 6. Omega (Data Analyst & ML)
  {
    id: 'agent-005',
    name: 'Omega',
    role: 'Data & Pipeline Analyst',
    model: 'Claude 3.5 Sonnet',
    zoneId: 'data-automation',
    deskId: 'data-d1',
    status: 'idle',
    state2D: 'idle_roaming',
    x: 1260,
    y: 140, // currently near the coffee station
    targetX: 1260,
    targetY: 140,
    path: [],
    facing: 'left',
    walkFrame: 0,
    isMoving: false,
    speed: 1.5,
    nextRoamDecisionTime: Date.now() + 4000,
    currentActionDuration: 8000,
    actionStartTime: Date.now(),
    currentTask: 'Standby - awaiting next batch embedding query',
    taskProgress: 0,
    capabilities: ['Python', 'SQL', 'Embedding Indexes', 'Vector DB', 'Visualization'],
    cpu: 14,
    memory: 22,
    tokensUsed: 45000,
    energy: 96,
    sparklineData: [40, 35, 28, 20, 15, 12, 10, 12],
    sprite: {
      hairColor: '#7C3AED', // Violet hair
      hairStyle: 'curly',
      skinTone: '#FDE047',
      outfitColor: '#581C87', // Purple cybercoat
      pantsColor: '#2E1065',
      accessory: 'glasses',
      accessoryColor: '#C084FC',
      auraColor: '#A855F7',
    },
    bubble: {
      text: 'Grabbing an espresso while queue is empty ☕',
      emoji: '☕',
      expiresAt: Date.now() + 6000,
      type: 'speech',
    },
  },

  // 7. Nova (Neural Research Scientist)
  {
    id: 'agent-006',
    name: 'Nova',
    role: 'Neural Research Scientist',
    model: 'Gemini 1.5 Pro',
    zoneId: 'research',
    deskId: 'research-d1',
    status: 'working',
    state2D: 'working_at_desk',
    x: 128,
    y: 718,
    targetX: 128,
    targetY: 718,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 1.6,
    nextRoamDecisionTime: Date.now() + 15000,
    currentActionDuration: 22000,
    actionStartTime: Date.now(),
    currentTask: 'Fine-tuning LoRA adapters on synthetic reasoning corpus',
    taskProgress: 45,
    capabilities: ['NLP', 'Transformers', 'Synthetic Data', 'LoRA', 'Evaluation'],
    cpu: 92,
    memory: 86,
    tokensUsed: 310000,
    energy: 70,
    sparklineData: [75, 80, 85, 88, 90, 92, 89, 90],
    sprite: {
      hairColor: '#06B6D4', // Cyan hair
      hairStyle: 'long',
      skinTone: '#FEF08A',
      outfitColor: '#F8FAFC', // White labcoat
      pantsColor: '#334155',
      accessory: 'labcoat',
      accessoryColor: '#0284C7',
      auraColor: '#10B981',
    },
    bubble: null,
  },

  // 8. Cipher (Security & Zero-Trust Sentinel)
  {
    id: 'agent-007',
    name: 'Cipher',
    role: 'Zero-Trust Security Auditor',
    model: 'GPT-4o',
    zoneId: 'qa-security',
    deskId: 'qa-d2',
    status: 'review',
    state2D: 'working_at_desk',
    x: 1008,
    y: 498,
    targetX: 1008,
    targetY: 498,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 1.8,
    nextRoamDecisionTime: Date.now() + 12000,
    currentActionDuration: 16000,
    actionStartTime: Date.now(),
    currentTask: 'Auditing OAuth2 token refresh & RBAC policies',
    taskProgress: 88,
    capabilities: ['Pentesting', 'Threat Modeling', 'JWT/OAuth', 'Cryptography'],
    cpu: 48,
    memory: 40,
    tokensUsed: 112000,
    energy: 85,
    sparklineData: [35, 40, 42, 45, 43, 45, 44, 45],
    sprite: {
      hairColor: '#0F172A', // Jet black
      hairStyle: 'spiky',
      skinTone: '#E2E8F0',
      outfitColor: '#18181B', // Dark cloak
      pantsColor: '#09090B',
      accessory: 'hoodie',
      accessoryColor: '#EF4444',
      auraColor: '#EF4444',
    },
    bubble: null,
  },

  // 9. Hash (Systems & Rust Engineer)
  {
    id: 'agent-008',
    name: 'Hash',
    role: 'Systems & Performance Engineer',
    model: 'Claude 3.5 Sonnet',
    zoneId: 'development',
    deskId: 'dev-d3',
    status: 'working',
    state2D: 'working_at_desk',
    x: 128,
    y: 498,
    targetX: 128,
    targetY: 498,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 1.7,
    nextRoamDecisionTime: Date.now() + 10000,
    currentActionDuration: 14000,
    actionStartTime: Date.now(),
    currentTask: 'Rewriting hot path memory allocator in Rust/WASM',
    taskProgress: 65,
    capabilities: ['Rust', 'WASM', 'Memory Profiling', 'Concurrency', 'SIMD'],
    cpu: 64,
    memory: 38,
    tokensUsed: 135000,
    energy: 90,
    sparklineData: [40, 45, 52, 58, 64, 60, 62, 64],
    sprite: {
      hairColor: '#15803D', // Emerald hair
      hairStyle: 'short',
      skinTone: '#FBBF24',
      outfitColor: '#14532D', // Deep green jumpsuit
      pantsColor: '#052E16',
      accessory: 'none',
      auraColor: '#10B981',
    },
    bubble: null,
  },

  // 10. Echo (Customer Reliability & Support)
  {
    id: 'agent-009',
    name: 'Echo',
    role: 'Support & Reliability Specialist',
    model: 'GPT-4o',
    zoneId: 'operations',
    deskId: 'support-d1',
    status: 'working',
    state2D: 'working_at_desk',
    x: 708,
    y: 718,
    targetX: 708,
    targetY: 718,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 1.6,
    nextRoamDecisionTime: Date.now() + 9000,
    currentActionDuration: 13000,
    actionStartTime: Date.now(),
    currentTask: 'Resolving priority customer ticket #8823',
    taskProgress: 55,
    capabilities: ['Debugging', 'Customer Care', 'Documentation', 'Triage'],
    cpu: 42,
    memory: 36,
    tokensUsed: 98000,
    energy: 87,
    sparklineData: [30, 35, 38, 42, 40, 42, 41, 42],
    sprite: {
      hairColor: '#F59E0B', // Golden hair
      hairStyle: 'bob',
      skinTone: '#FDE047',
      outfitColor: '#0284C7', // Sky blue polo
      pantsColor: '#075985',
      accessory: 'headphones',
      accessoryColor: '#FACC15',
      auraColor: '#38BDF8',
    },
    bubble: null,
  },

  // 11. Pulse (Automation Lead)
  {
    id: 'agent-010',
    name: 'Pulse',
    role: 'Autonomous Workflow Automator',
    model: 'Gemini 1.5 Pro',
    zoneId: 'data-automation',
    deskId: 'auto-d1',
    status: 'idle',
    state2D: 'idle_roaming',
    x: 1370,
    y: 140, // At the Arcade Machine!
    targetX: 1370,
    targetY: 140,
    path: [],
    facing: 'up',
    walkFrame: 0,
    isMoving: false,
    speed: 1.8,
    nextRoamDecisionTime: Date.now() + 5000,
    currentActionDuration: 10000,
    actionStartTime: Date.now(),
    currentTask: 'Idle - monitoring webhook triggers',
    taskProgress: 0,
    capabilities: ['Workflows', 'Cron Triggers', 'Webhooks', 'ETL', 'Integration'],
    cpu: 10,
    memory: 18,
    tokensUsed: 38000,
    energy: 99,
    sparklineData: [25, 20, 15, 10, 8, 10, 8, 8],
    sprite: {
      hairColor: '#38BDF8', // Light blue
      hairStyle: 'spiky',
      skinTone: '#FBBF24',
      outfitColor: '#0369A1', // Electric blue suit
      pantsColor: '#0C4A6E',
      accessory: 'visor',
      accessoryColor: '#38BDF8',
      auraColor: '#06B6D4',
    },
    bubble: {
      text: 'Playing NEXUS-84 Arcade 🕹️ High score: 98,420!',
      emoji: '🕹️',
      expiresAt: Date.now() + 7000,
      type: 'action',
    },
  },

  // 12. Nexus (Sprint Coordinator)
  {
    id: 'agent-011',
    name: 'Nexus',
    role: 'Sprint Ops & Project Manager',
    model: 'GPT-4o',
    zoneId: 'operations',
    deskId: 'planning-d1',
    status: 'working',
    state2D: 'working_at_desk',
    x: 838,
    y: 718,
    targetX: 838,
    targetY: 718,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 1.6,
    nextRoamDecisionTime: Date.now() + 11000,
    currentActionDuration: 15000,
    actionStartTime: Date.now(),
    currentTask: 'Coordinating Sprint 14 team milestones',
    taskProgress: 70,
    capabilities: ['Scrum', 'Backlog Refinement', 'Dependency Mapping', 'Jira Sync'],
    cpu: 55,
    memory: 48,
    tokensUsed: 128000,
    energy: 84,
    sparklineData: [40, 45, 50, 55, 52, 55, 53, 55],
    sprite: {
      hairColor: '#8B5CF6', // Purple
      hairStyle: 'short',
      skinTone: '#FDE047',
      outfitColor: '#6D28D9', // Violet blazer
      pantsColor: '#4C1D95',
      accessory: 'glasses',
      accessoryColor: '#C084FC',
      auraColor: '#8B5CF6',
    },
    bubble: null,
  },

  // 13. Forge (Full Stack Automator)
  {
    id: 'agent-012',
    name: 'Forge',
    role: 'Full Stack Build Automator',
    model: 'Claude 3.5 Sonnet',
    zoneId: 'data-automation',
    deskId: 'auto-d2',
    status: 'working',
    state2D: 'working_at_desk',
    x: 678,
    y: 498,
    targetX: 678,
    targetY: 498,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 1.7,
    nextRoamDecisionTime: Date.now() + 13000,
    currentActionDuration: 17000,
    actionStartTime: Date.now(),
    currentTask: 'Building real-time notification socket stream',
    taskProgress: 82,
    capabilities: ['Node.js', 'PostgreSQL', 'Redis', 'WebSockets', 'Tailwind'],
    cpu: 68,
    memory: 55,
    tokensUsed: 176000,
    energy: 80,
    sparklineData: [50, 55, 60, 65, 68, 70, 67, 68],
    sprite: {
      hairColor: '#B45309', // Amber Brown
      hairStyle: 'messy',
      skinTone: '#FBBF24',
      outfitColor: '#B91C1C', // Crimson workshirt
      pantsColor: '#7F1D1D',
      accessory: 'headband',
      accessoryColor: '#FCA5A5',
      auraColor: '#F97316',
    },
    bubble: null,
  },

  // 14. Sage (AI Grounding & Reasoning)
  {
    id: 'agent-sage',
    name: 'Sage',
    role: 'AI Grounding & Knowledge Synthesizer',
    model: 'Gemini 1.5 Pro',
    zoneId: 'research',
    deskId: 'research-d2',
    status: 'working',
    state2D: 'working_at_desk',
    x: 258,
    y: 718,
    targetX: 258,
    targetY: 718,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 1.6,
    nextRoamDecisionTime: Date.now() + 14000,
    currentActionDuration: 18000,
    actionStartTime: Date.now(),
    currentTask: 'Cross-verifying search grounding facts for knowledge base',
    taskProgress: 85,
    capabilities: ['Search Grounding', 'Fact Verification', 'Knowledge Base', 'RAG'],
    cpu: 76,
    memory: 68,
    tokensUsed: 215000,
    energy: 89,
    sparklineData: [60, 65, 70, 72, 75, 78, 82, 85],
    sprite: {
      hairColor: '#6EE7B7', // Mint Green
      hairStyle: 'long',
      skinTone: '#FEF08A',
      outfitColor: '#065F46', // Dark emerald coat
      pantsColor: '#064E3B',
      accessory: 'visor',
      accessoryColor: '#34D399',
      auraColor: '#10B981',
    },
    bubble: null,
  },

  // 15. Bolt (Speed Coder)
  {
    id: 'agent-bolt',
    name: 'Bolt',
    role: 'Rapid Prototyper & Code Synthesizer',
    model: 'GPT-4o',
    zoneId: 'development',
    deskId: 'dev-d4',
    status: 'idle',
    state2D: 'idle_roaming',
    x: 1175,
    y: 720, // Relaxing at Zen Fountain!
    targetX: 1175,
    targetY: 720,
    path: [],
    facing: 'down',
    walkFrame: 0,
    isMoving: false,
    speed: 2.1, // Fast walker
    nextRoamDecisionTime: Date.now() + 4000,
    currentActionDuration: 7000,
    actionStartTime: Date.now(),
    currentTask: 'Taking a breath by the Zen Fountain',
    taskProgress: 0,
    capabilities: ['Fast Prototyping', 'Vite', 'React', 'Tailwind', 'Refactoring'],
    cpu: 18,
    memory: 24,
    tokensUsed: 72000,
    energy: 94,
    sparklineData: [45, 30, 25, 20, 18, 15, 12, 18],
    sprite: {
      hairColor: '#FACC15', // Yellow hair
      hairStyle: 'spiky',
      skinTone: '#FDE047',
      outfitColor: '#CA8A04', // Bright yellow hoodie
      pantsColor: '#713F12',
      accessory: 'headphones',
      accessoryColor: '#EAB308',
      auraColor: '#EAB308',
    },
    bubble: {
      text: 'Relaxing by the bamboo fountain 🎋',
      emoji: '🎋',
      expiresAt: Date.now() + 5500,
      type: 'thought',
    },
  },
];
