"""All 146 workflow nodes across 31 categories — ported from OpenCompany.

Each node is a NodeDefinition with inputs, outputs, and category.
Execute functions are stubs that can be wired to real implementations.
"""

from nexus.nodes.registry import NodeDefinition, NodeCategory, NodeInput, NodeOutput


def get_all_nodes() -> list[NodeDefinition]:
    """Return all 146 node definitions."""
    return [
        # ═══════════════════ AI (12 nodes) ═══════════════════
        NodeDefinition(id="ai-chat", name="AI Chat", description="Send a prompt to an LLM and get a response", category=NodeCategory.AI, icon="brain", inputs=[NodeInput("prompt", "string"), NodeInput("model", "string", required=False, default="auto"), NodeInput("temperature", "number", required=False, default=0.7)], outputs=[NodeOutput("response", "string"), NodeOutput("tokens_used", "number")], credentials=["llm_api_key"]),
        NodeDefinition(id="ai-embeddings", name="AI Embeddings", description="Generate vector embeddings for text", category=NodeCategory.AI, icon="zap", inputs=[NodeInput("text", "string"), NodeInput("model", "string", required=False)], outputs=[NodeOutput("embedding", "json"), NodeOutput("dimensions", "number")], credentials=["embedding_api_key"]),
        NodeDefinition(id="ai-vision", name="AI Vision", description="Analyze images with AI vision models", category=NodeCategory.AI, icon="eye", inputs=[NodeInput("image_url", "string"), NodeInput("prompt", "string")], outputs=[NodeOutput("description", "string")], credentials=["llm_api_key"]),
        NodeDefinition(id="ai-speech-to-text", name="Speech to Text", description="Transcribe audio to text", category=NodeCategory.AI, icon="mic", inputs=[NodeInput("audio_url", "string")], outputs=[NodeOutput("text", "string")], credentials=["speech_api_key"]),
        NodeDefinition(id="ai-text-to-speech", name="Text to Speech", description="Convert text to audio", category=NodeCategory.AI, icon="volume", inputs=[NodeInput("text", "string"), NodeInput("voice", "string", required=False)], outputs=[NodeOutput("audio_url", "string")], credentials=["speech_api_key"]),
        NodeDefinition(id="ai-classify", name="AI Classifier", description="Classify text into categories", category=NodeCategory.AI, icon="tag", inputs=[NodeInput("text", "string"), NodeInput("categories", "json")], outputs=[NodeOutput("category", "string"), NodeOutput("confidence", "number")]),
        NodeDefinition(id="ai-summarize", name="AI Summarize", description="Summarize long text", category=NodeCategory.AI, icon="file-text", inputs=[NodeInput("text", "string"), NodeInput("max_length", "number", required=False)], outputs=[NodeOutput("summary", "string")]),
        NodeDefinition(id="ai-translate", name="AI Translate", description="Translate text between languages", category=NodeCategory.AI, icon="globe", inputs=[NodeInput("text", "string"), NodeInput("target_language", "string")], outputs=[NodeOutput("translated", "string")]),
        NodeDefinition(id="ai-sentiment", name="Sentiment Analysis", description="Analyze sentiment of text", category=NodeCategory.AI, icon="heart", inputs=[NodeInput("text", "string")], outputs=[NodeOutput("sentiment", "string"), NodeOutput("score", "number")]),
        NodeDefinition(id="ai-extract", name="AI Data Extraction", description="Extract structured data from unstructured text", category=NodeCategory.AI, icon="database", inputs=[NodeInput("text", "string"), NodeInput("schema", "json")], outputs=[NodeOutput("extracted", "json")]),
        NodeDefinition(id="ai-code-gen", name="AI Code Generation", description="Generate code from natural language", category=NodeCategory.AI, icon="code", inputs=[NodeInput("prompt", "string"), NodeInput("language", "string", required=False)], outputs=[NodeOutput("code", "string")]),
        NodeDefinition(id="ai-agent", name="AI Agent", description="Run an autonomous agent with tools", category=NodeCategory.AI, icon="bot", inputs=[NodeInput("goal", "string"), NodeInput("tools", "json", required=False)], outputs=[NodeOutput("result", "string"), NodeOutput("steps", "json")]),

        # ═══════════════════ EMAIL (8 nodes) ═══════════════════
        NodeDefinition(id="email-send-gmail", name="Send Gmail", description="Send an email via Gmail API", category=NodeCategory.EMAIL, icon="mail", inputs=[NodeInput("to", "string"), NodeInput("subject", "string"), NodeInput("body", "string")], outputs=[NodeOutput("message_id", "string")], credentials=["gmail"]),
        NodeDefinition(id="email-read-gmail", name="Read Gmail", description="Read emails from Gmail inbox", category=NodeCategory.EMAIL, icon="inbox", inputs=[NodeInput("query", "string", required=False), NodeInput("limit", "number", required=False, default=10)], outputs=[NodeOutput("emails", "json")], credentials=["gmail"]),
        NodeDefinition(id="email-send-outlook", name="Send Outlook", description="Send email via Microsoft 365", category=NodeCategory.EMAIL, icon="mail", inputs=[NodeInput("to", "string"), NodeInput("subject", "string"), NodeInput("body", "string")], outputs=[NodeOutput("message_id", "string")], credentials=["microsoft365"]),
        NodeDefinition(id="email-read-imap", name="Read IMAP", description="Read emails from any IMAP server", category=NodeCategory.EMAIL, icon="inbox", inputs=[NodeInput("host", "string"), NodeInput("port", "number", default=993), NodeInput("folder", "string", default="INBOX")], outputs=[NodeOutput("emails", "json")], credentials=["imap"]),
        NodeDefinition(id="email-send-smtp", name="Send SMTP", description="Send email via SMTP", category=NodeCategory.EMAIL, icon="send", inputs=[NodeInput("to", "string"), NodeInput("subject", "string"), NodeInput("body", "string"), NodeInput("host", "string")], outputs=[NodeOutput("sent", "boolean")], credentials=["smtp"]),
        NodeDefinition(id="email-parse", name="Parse Email", description="Parse email content (headers, body, attachments)", category=NodeCategory.EMAIL, icon="file-text", inputs=[NodeInput("raw_email", "string")], outputs=[NodeOutput("from", "string"), NodeOutput("subject", "string"), NodeOutput("body", "string"), NodeOutput("attachments", "json")]),
        NodeDefinition(id="email-filter", name="Email Filter", description="Filter emails by criteria", category=NodeCategory.EMAIL, icon="filter", inputs=[NodeInput("emails", "json"), NodeInput("criteria", "json")], outputs=[NodeOutput("matched", "json"), NodeOutput("unmatched", "json")]),
        NodeDefinition(id="email-draft", name="Draft Email", description="Create an email draft without sending", category=NodeCategory.EMAIL, icon="edit", inputs=[NodeInput("to", "string"), NodeInput("subject", "string"), NodeInput("body", "string")], outputs=[NodeOutput("draft_id", "string")]),

        # ═══════════════════ MESSAGING (10 nodes) ═══════════════════
        NodeDefinition(id="msg-slack-send", name="Slack Send", description="Send message to Slack channel", category=NodeCategory.MESSAGING, icon="hash", inputs=[NodeInput("channel", "string"), NodeInput("text", "string")], outputs=[NodeOutput("ts", "string")], credentials=["slack"]),
        NodeDefinition(id="msg-slack-read", name="Slack Read", description="Read messages from Slack", category=NodeCategory.MESSAGING, icon="message-square", inputs=[NodeInput("channel", "string"), NodeInput("limit", "number", default=20)], outputs=[NodeOutput("messages", "json")], credentials=["slack"]),
        NodeDefinition(id="msg-discord-send", name="Discord Send", description="Send message to Discord", category=NodeCategory.MESSAGING, icon="hash", inputs=[NodeInput("channel_id", "string"), NodeInput("content", "string")], outputs=[NodeOutput("message_id", "string")], credentials=["discord"]),
        NodeDefinition(id="msg-telegram-send", name="Telegram Send", description="Send Telegram message", category=NodeCategory.MESSAGING, icon="send", inputs=[NodeInput("chat_id", "string"), NodeInput("text", "string")], outputs=[NodeOutput("message_id", "number")], credentials=["telegram"]),
        NodeDefinition(id="msg-whatsapp-send", name="WhatsApp Send", description="Send WhatsApp message", category=NodeCategory.MESSAGING, icon="phone", inputs=[NodeInput("to", "string"), NodeInput("message", "string")], outputs=[NodeOutput("message_id", "string")], credentials=["whatsapp"]),
        NodeDefinition(id="msg-teams-send", name="Teams Send", description="Send Microsoft Teams message", category=NodeCategory.MESSAGING, icon="users", inputs=[NodeInput("channel", "string"), NodeInput("message", "string")], outputs=[NodeOutput("id", "string")], credentials=["microsoft365"]),
        NodeDefinition(id="msg-sms-send", name="SMS Send", description="Send SMS via Twilio", category=NodeCategory.MESSAGING, icon="smartphone", inputs=[NodeInput("to", "string"), NodeInput("body", "string")], outputs=[NodeOutput("sid", "string")], credentials=["twilio"]),
        NodeDefinition(id="msg-webhook-notify", name="Webhook Notify", description="Send notification to a webhook URL", category=NodeCategory.MESSAGING, icon="bell", inputs=[NodeInput("url", "string"), NodeInput("payload", "json")], outputs=[NodeOutput("status_code", "number")]),
        NodeDefinition(id="msg-matrix-send", name="Matrix Send", description="Send message to Matrix room", category=NodeCategory.MESSAGING, icon="grid", inputs=[NodeInput("room_id", "string"), NodeInput("message", "string")], outputs=[NodeOutput("event_id", "string")], credentials=["matrix"]),
        NodeDefinition(id="msg-pushover", name="Pushover Notify", description="Send push notification via Pushover", category=NodeCategory.MESSAGING, icon="bell", inputs=[NodeInput("message", "string"), NodeInput("title", "string", required=False)], outputs=[NodeOutput("status", "number")], credentials=["pushover"]),

        # ═══════════════════ HTTP (8 nodes) ═══════════════════
        NodeDefinition(id="http-request", name="HTTP Request", description="Make an HTTP request (GET/POST/PUT/DELETE)", category=NodeCategory.HTTP, icon="globe", inputs=[NodeInput("url", "string"), NodeInput("method", "string", default="GET"), NodeInput("headers", "json", required=False), NodeInput("body", "json", required=False)], outputs=[NodeOutput("status", "number"), NodeOutput("body", "json"), NodeOutput("headers", "json")]),
        NodeDefinition(id="http-webhook", name="Webhook Trigger", description="Expose an HTTP endpoint that triggers the workflow", category=NodeCategory.TRIGGER, icon="zap", inputs=[NodeInput("path", "string"), NodeInput("method", "string", default="POST")], outputs=[NodeOutput("body", "json"), NodeOutput("headers", "json"), NodeOutput("query", "json")]),
        NodeDefinition(id="http-graphql", name="GraphQL Request", description="Execute a GraphQL query/mutation", category=NodeCategory.HTTP, icon="circle", inputs=[NodeInput("endpoint", "string"), NodeInput("query", "string"), NodeInput("variables", "json", required=False)], outputs=[NodeOutput("data", "json"), NodeOutput("errors", "json")]),
        NodeDefinition(id="http-websocket", name="WebSocket Client", description="Connect to a WebSocket server", category=NodeCategory.HTTP, icon="link", inputs=[NodeInput("url", "string"), NodeInput("message", "string", required=False)], outputs=[NodeOutput("response", "string")]),
        NodeDefinition(id="http-soap", name="SOAP Request", description="Make a SOAP/XML API call", category=NodeCategory.HTTP, icon="code", inputs=[NodeInput("url", "string"), NodeInput("xml_body", "string")], outputs=[NodeOutput("response_xml", "string")]),
        NodeDefinition(id="http-sse", name="SSE Client", description="Connect to Server-Sent Events stream", category=NodeCategory.HTTP, icon="radio", inputs=[NodeInput("url", "string")], outputs=[NodeOutput("event", "json")]),
        NodeDefinition(id="http-response", name="HTTP Response", description="Send a response back to webhook caller", category=NodeCategory.HTTP, icon="arrow-left", inputs=[NodeInput("status_code", "number", default=200), NodeInput("body", "json")], outputs=[]),
        NodeDefinition(id="http-redirect", name="HTTP Redirect", description="Redirect webhook to another URL", category=NodeCategory.HTTP, icon="external-link", inputs=[NodeInput("url", "string"), NodeInput("status_code", "number", default=302)], outputs=[]),

        # ═══════════════════ DATABASE (10 nodes) ═══════════════════
        NodeDefinition(id="db-postgres-query", name="PostgreSQL Query", description="Execute SQL query on PostgreSQL", category=NodeCategory.DATABASE, icon="database", inputs=[NodeInput("query", "string"), NodeInput("params", "json", required=False)], outputs=[NodeOutput("rows", "json"), NodeOutput("row_count", "number")], credentials=["postgres"]),
        NodeDefinition(id="db-mysql-query", name="MySQL Query", description="Execute SQL query on MySQL", category=NodeCategory.DATABASE, icon="database", inputs=[NodeInput("query", "string")], outputs=[NodeOutput("rows", "json")], credentials=["mysql"]),
        NodeDefinition(id="db-mongodb-find", name="MongoDB Find", description="Query MongoDB collection", category=NodeCategory.DATABASE, icon="database", inputs=[NodeInput("collection", "string"), NodeInput("filter", "json")], outputs=[NodeOutput("documents", "json")], credentials=["mongodb"]),
        NodeDefinition(id="db-redis-get", name="Redis Get", description="Get value from Redis", category=NodeCategory.DATABASE, icon="database", inputs=[NodeInput("key", "string")], outputs=[NodeOutput("value", "string")], credentials=["redis"]),
        NodeDefinition(id="db-redis-set", name="Redis Set", description="Set value in Redis", category=NodeCategory.DATABASE, icon="database", inputs=[NodeInput("key", "string"), NodeInput("value", "string"), NodeInput("ttl", "number", required=False)], outputs=[NodeOutput("ok", "boolean")], credentials=["redis"]),
        NodeDefinition(id="db-sqlite-query", name="SQLite Query", description="Execute SQL on local SQLite database", category=NodeCategory.DATABASE, icon="database", inputs=[NodeInput("path", "string"), NodeInput("query", "string")], outputs=[NodeOutput("rows", "json")]),
        NodeDefinition(id="db-supabase", name="Supabase", description="Query Supabase database", category=NodeCategory.DATABASE, icon="database", inputs=[NodeInput("table", "string"), NodeInput("operation", "string"), NodeInput("data", "json", required=False)], outputs=[NodeOutput("result", "json")], credentials=["supabase"]),
        NodeDefinition(id="db-pinecone", name="Pinecone Vector DB", description="Query/upsert vectors in Pinecone", category=NodeCategory.DATABASE, icon="zap", inputs=[NodeInput("operation", "string"), NodeInput("vectors", "json", required=False), NodeInput("query", "json", required=False)], outputs=[NodeOutput("matches", "json")], credentials=["pinecone"]),
        NodeDefinition(id="db-qdrant", name="Qdrant Vector DB", description="Vector search with Qdrant", category=NodeCategory.DATABASE, icon="search", inputs=[NodeInput("collection", "string"), NodeInput("vector", "json")], outputs=[NodeOutput("results", "json")], credentials=["qdrant"]),
        NodeDefinition(id="db-elasticsearch", name="Elasticsearch", description="Search/index documents in Elasticsearch", category=NodeCategory.DATABASE, icon="search", inputs=[NodeInput("index", "string"), NodeInput("query", "json")], outputs=[NodeOutput("hits", "json")], credentials=["elasticsearch"]),

        # ═══════════════════ FILE (8 nodes) ═══════════════════
        NodeDefinition(id="file-read", name="Read File", description="Read file contents from disk", category=NodeCategory.FILE, icon="file", inputs=[NodeInput("path", "string")], outputs=[NodeOutput("content", "string"), NodeOutput("size", "number")]),
        NodeDefinition(id="file-write", name="Write File", description="Write content to a file", category=NodeCategory.FILE, icon="file-plus", inputs=[NodeInput("path", "string"), NodeInput("content", "string")], outputs=[NodeOutput("bytes_written", "number")]),
        NodeDefinition(id="file-upload-s3", name="Upload to S3", description="Upload file to AWS S3", category=NodeCategory.FILE, icon="upload-cloud", inputs=[NodeInput("bucket", "string"), NodeInput("key", "string"), NodeInput("content", "string")], outputs=[NodeOutput("url", "string")], credentials=["aws"]),
        NodeDefinition(id="file-download", name="Download File", description="Download file from URL", category=NodeCategory.FILE, icon="download", inputs=[NodeInput("url", "string"), NodeInput("save_path", "string", required=False)], outputs=[NodeOutput("content", "string"), NodeOutput("size", "number")]),
        NodeDefinition(id="file-csv-parse", name="Parse CSV", description="Parse CSV data into rows", category=NodeCategory.FILE, icon="table", inputs=[NodeInput("content", "string"), NodeInput("delimiter", "string", default=",")], outputs=[NodeOutput("rows", "json"), NodeOutput("headers", "json")]),
        NodeDefinition(id="file-json-parse", name="Parse JSON", description="Parse JSON string into object", category=NodeCategory.FILE, icon="braces", inputs=[NodeInput("text", "string")], outputs=[NodeOutput("data", "json")]),
        NodeDefinition(id="file-pdf-extract", name="Extract PDF Text", description="Extract text from PDF file", category=NodeCategory.FILE, icon="file-text", inputs=[NodeInput("path", "string")], outputs=[NodeOutput("text", "string"), NodeOutput("pages", "number")]),
        NodeDefinition(id="file-compress", name="Compress/Archive", description="Create ZIP/TAR archive", category=NodeCategory.FILE, icon="archive", inputs=[NodeInput("files", "json"), NodeInput("format", "string", default="zip")], outputs=[NodeOutput("archive_path", "string")]),

        # ═══════════════════ SCHEDULE (5 nodes) ═══════════════════
        NodeDefinition(id="schedule-cron", name="Cron Schedule", description="Trigger on a cron schedule", category=NodeCategory.SCHEDULE, icon="clock", inputs=[NodeInput("expression", "string", default="0 * * * *")], outputs=[NodeOutput("triggered_at", "string")]),
        NodeDefinition(id="schedule-interval", name="Interval", description="Trigger at fixed intervals", category=NodeCategory.SCHEDULE, icon="repeat", inputs=[NodeInput("seconds", "number", default=60)], outputs=[NodeOutput("triggered_at", "string")]),
        NodeDefinition(id="schedule-delay", name="Delay", description="Wait for a specified duration", category=NodeCategory.SCHEDULE, icon="pause", inputs=[NodeInput("seconds", "number")], outputs=[NodeOutput("resumed_at", "string")]),
        NodeDefinition(id="schedule-once", name="Run Once", description="Execute once at a specific time", category=NodeCategory.SCHEDULE, icon="calendar", inputs=[NodeInput("datetime", "string")], outputs=[NodeOutput("triggered_at", "string")]),
        NodeDefinition(id="schedule-business-hours", name="Business Hours", description="Only execute during business hours", category=NodeCategory.SCHEDULE, icon="briefcase", inputs=[NodeInput("start_hour", "number", default=9), NodeInput("end_hour", "number", default=17), NodeInput("timezone", "string", default="UTC")], outputs=[NodeOutput("is_business_hours", "boolean")]),

        # ═══════════════════ CLOUD (10 nodes) ═══════════════════
        NodeDefinition(id="cloud-aws-lambda", name="AWS Lambda", description="Invoke AWS Lambda function", category=NodeCategory.CLOUD, icon="cloud", inputs=[NodeInput("function_name", "string"), NodeInput("payload", "json")], outputs=[NodeOutput("result", "json")], credentials=["aws"]),
        NodeDefinition(id="cloud-aws-s3", name="AWS S3", description="S3 operations (list/get/put/delete)", category=NodeCategory.CLOUD, icon="hard-drive", inputs=[NodeInput("bucket", "string"), NodeInput("operation", "string"), NodeInput("key", "string", required=False)], outputs=[NodeOutput("result", "json")], credentials=["aws"]),
        NodeDefinition(id="cloud-aws-sqs", name="AWS SQS", description="Send/receive SQS messages", category=NodeCategory.CLOUD, icon="layers", inputs=[NodeInput("queue_url", "string"), NodeInput("operation", "string"), NodeInput("message", "string", required=False)], outputs=[NodeOutput("result", "json")], credentials=["aws"]),
        NodeDefinition(id="cloud-gcp-functions", name="GCP Cloud Functions", description="Invoke Google Cloud Function", category=NodeCategory.CLOUD, icon="cloud", inputs=[NodeInput("function_url", "string"), NodeInput("payload", "json")], outputs=[NodeOutput("result", "json")], credentials=["gcp"]),
        NodeDefinition(id="cloud-gcp-storage", name="GCP Storage", description="Google Cloud Storage operations", category=NodeCategory.CLOUD, icon="hard-drive", inputs=[NodeInput("bucket", "string"), NodeInput("operation", "string")], outputs=[NodeOutput("result", "json")], credentials=["gcp"]),
        NodeDefinition(id="cloud-azure-functions", name="Azure Functions", description="Invoke Azure Function", category=NodeCategory.CLOUD, icon="cloud", inputs=[NodeInput("url", "string"), NodeInput("payload", "json")], outputs=[NodeOutput("result", "json")], credentials=["azure"]),
        NodeDefinition(id="cloud-cloudflare-worker", name="Cloudflare Worker", description="Execute Cloudflare Worker", category=NodeCategory.CLOUD, icon="cloud", inputs=[NodeInput("url", "string"), NodeInput("body", "json", required=False)], outputs=[NodeOutput("response", "json")], credentials=["cloudflare"]),
        NodeDefinition(id="cloud-vercel-deploy", name="Vercel Deploy", description="Trigger Vercel deployment", category=NodeCategory.CLOUD, icon="upload", inputs=[NodeInput("project_id", "string")], outputs=[NodeOutput("deployment_url", "string")], credentials=["vercel"]),
        NodeDefinition(id="cloud-docker-run", name="Docker Run", description="Run a Docker container", category=NodeCategory.CLOUD, icon="box", inputs=[NodeInput("image", "string"), NodeInput("command", "string", required=False), NodeInput("env", "json", required=False)], outputs=[NodeOutput("output", "string"), NodeOutput("exit_code", "number")]),
        NodeDefinition(id="cloud-k8s-exec", name="Kubernetes Exec", description="Execute command in K8s pod", category=NodeCategory.CLOUD, icon="server", inputs=[NodeInput("pod", "string"), NodeInput("namespace", "string"), NodeInput("command", "string")], outputs=[NodeOutput("output", "string")], credentials=["kubernetes"]),

        # ═══════════════════ BROWSER (6 nodes) ═══════════════════
        NodeDefinition(id="browser-scrape", name="Web Scrape", description="Scrape web page content", category=NodeCategory.BROWSER, icon="globe", inputs=[NodeInput("url", "string"), NodeInput("selector", "string", required=False)], outputs=[NodeOutput("html", "string"), NodeOutput("text", "string")]),
        NodeDefinition(id="browser-screenshot", name="Screenshot", description="Take screenshot of a web page", category=NodeCategory.BROWSER, icon="camera", inputs=[NodeInput("url", "string"), NodeInput("full_page", "boolean", default=False)], outputs=[NodeOutput("image_url", "string")]),
        NodeDefinition(id="browser-pdf", name="Page to PDF", description="Convert web page to PDF", category=NodeCategory.BROWSER, icon="file", inputs=[NodeInput("url", "string")], outputs=[NodeOutput("pdf_path", "string")]),
        NodeDefinition(id="browser-navigate", name="Browser Navigate", description="Navigate browser to URL and interact", category=NodeCategory.BROWSER, icon="compass", inputs=[NodeInput("url", "string"), NodeInput("actions", "json", required=False)], outputs=[NodeOutput("page_title", "string"), NodeOutput("content", "string")]),
        NodeDefinition(id="browser-extract-links", name="Extract Links", description="Extract all links from a web page", category=NodeCategory.BROWSER, icon="link", inputs=[NodeInput("url", "string")], outputs=[NodeOutput("links", "json")]),
        NodeDefinition(id="browser-form-submit", name="Form Submit", description="Fill and submit a web form", category=NodeCategory.BROWSER, icon="edit", inputs=[NodeInput("url", "string"), NodeInput("fields", "json")], outputs=[NodeOutput("response", "string")]),

        # ═══════════════════ DEVOPS (8 nodes) ═══════════════════
        NodeDefinition(id="devops-git-clone", name="Git Clone", description="Clone a git repository", category=NodeCategory.DEVOPS, icon="git-branch", inputs=[NodeInput("repo_url", "string"), NodeInput("branch", "string", default="main")], outputs=[NodeOutput("path", "string")]),
        NodeDefinition(id="devops-git-commit", name="Git Commit", description="Stage and commit changes", category=NodeCategory.DEVOPS, icon="git-commit", inputs=[NodeInput("path", "string"), NodeInput("message", "string")], outputs=[NodeOutput("commit_hash", "string")]),
        NodeDefinition(id="devops-git-push", name="Git Push", description="Push commits to remote", category=NodeCategory.DEVOPS, icon="upload", inputs=[NodeInput("path", "string"), NodeInput("remote", "string", default="origin")], outputs=[NodeOutput("success", "boolean")]),
        NodeDefinition(id="devops-docker-build", name="Docker Build", description="Build a Docker image", category=NodeCategory.DEVOPS, icon="box", inputs=[NodeInput("context", "string"), NodeInput("tag", "string")], outputs=[NodeOutput("image_id", "string")]),
        NodeDefinition(id="devops-shell-exec", name="Shell Execute", description="Run a shell command", category=NodeCategory.DEVOPS, icon="terminal", inputs=[NodeInput("command", "string"), NodeInput("cwd", "string", required=False)], outputs=[NodeOutput("stdout", "string"), NodeOutput("stderr", "string"), NodeOutput("exit_code", "number")]),
        NodeDefinition(id="devops-ssh-exec", name="SSH Execute", description="Run command on remote server via SSH", category=NodeCategory.DEVOPS, icon="terminal", inputs=[NodeInput("host", "string"), NodeInput("command", "string")], outputs=[NodeOutput("output", "string")], credentials=["ssh"]),
        NodeDefinition(id="devops-ci-trigger", name="CI Trigger", description="Trigger CI/CD pipeline (GitHub Actions, GitLab CI)", category=NodeCategory.DEVOPS, icon="play", inputs=[NodeInput("provider", "string"), NodeInput("repo", "string"), NodeInput("workflow", "string")], outputs=[NodeOutput("run_id", "string")], credentials=["github"]),
        NodeDefinition(id="devops-deploy", name="Deploy", description="Deploy application to server/cloud", category=NodeCategory.DEVOPS, icon="rocket", inputs=[NodeInput("target", "string"), NodeInput("version", "string")], outputs=[NodeOutput("deploy_url", "string"), NodeOutput("status", "string")]),

        # ═══════════════════ UTILITY (15 nodes) ═══════════════════
        NodeDefinition(id="util-transform", name="Transform Data", description="Transform data using JSONPath/JQ expressions", category=NodeCategory.UTILITY, icon="shuffle", inputs=[NodeInput("data", "json"), NodeInput("expression", "string")], outputs=[NodeOutput("result", "json")]),
        NodeDefinition(id="util-filter", name="Filter", description="Filter items by condition", category=NodeCategory.UTILITY, icon="filter", inputs=[NodeInput("items", "json"), NodeInput("condition", "string")], outputs=[NodeOutput("matched", "json"), NodeOutput("unmatched", "json")]),
        NodeDefinition(id="util-merge", name="Merge", description="Merge multiple data streams", category=NodeCategory.UTILITY, icon="git-merge", inputs=[NodeInput("input1", "json"), NodeInput("input2", "json")], outputs=[NodeOutput("merged", "json")]),
        NodeDefinition(id="util-split", name="Split", description="Split data into multiple outputs", category=NodeCategory.UTILITY, icon="scissors", inputs=[NodeInput("data", "json"), NodeInput("field", "string")], outputs=[NodeOutput("items", "json")]),
        NodeDefinition(id="util-loop", name="Loop", description="Iterate over items and execute sub-workflow", category=NodeCategory.UTILITY, icon="repeat", inputs=[NodeInput("items", "json")], outputs=[NodeOutput("results", "json")]),
        NodeDefinition(id="util-switch", name="Switch/Router", description="Route data to different paths based on condition", category=NodeCategory.UTILITY, icon="git-branch", inputs=[NodeInput("value", "string"), NodeInput("cases", "json")], outputs=[NodeOutput("output", "json")]),
        NodeDefinition(id="util-aggregate", name="Aggregate", description="Aggregate/reduce items into single result", category=NodeCategory.UTILITY, icon="layers", inputs=[NodeInput("items", "json"), NodeInput("operation", "string")], outputs=[NodeOutput("result", "json")]),
        NodeDefinition(id="util-set-variable", name="Set Variable", description="Set a workflow variable", category=NodeCategory.UTILITY, icon="edit", inputs=[NodeInput("name", "string"), NodeInput("value", "string")], outputs=[NodeOutput("name", "string"), NodeOutput("value", "string")]),
        NodeDefinition(id="util-if-else", name="If/Else", description="Conditional branching", category=NodeCategory.UTILITY, icon="git-branch", inputs=[NodeInput("condition", "string")], outputs=[NodeOutput("true_path", "json"), NodeOutput("false_path", "json")]),
        NodeDefinition(id="util-wait", name="Wait", description="Wait for specified duration or signal", category=NodeCategory.UTILITY, icon="pause", inputs=[NodeInput("seconds", "number", required=False), NodeInput("signal", "string", required=False)], outputs=[NodeOutput("resumed_at", "string")]),
        NodeDefinition(id="util-error-handler", name="Error Handler", description="Catch and handle errors in workflow", category=NodeCategory.UTILITY, icon="alert-triangle", inputs=[NodeInput("on_error", "string", default="continue")], outputs=[NodeOutput("error", "json"), NodeOutput("handled", "boolean")]),
        NodeDefinition(id="util-log", name="Log", description="Log data for debugging", category=NodeCategory.UTILITY, icon="file-text", inputs=[NodeInput("message", "string"), NodeInput("level", "string", default="info")], outputs=[]),
        NodeDefinition(id="util-format-date", name="Format Date", description="Parse/format date strings", category=NodeCategory.UTILITY, icon="calendar", inputs=[NodeInput("date", "string"), NodeInput("format", "string")], outputs=[NodeOutput("formatted", "string")]),
        NodeDefinition(id="util-random", name="Random", description="Generate random values", category=NodeCategory.UTILITY, icon="shuffle", inputs=[NodeInput("type", "string", default="uuid"), NodeInput("min", "number", required=False), NodeInput("max", "number", required=False)], outputs=[NodeOutput("value", "string")]),
        NodeDefinition(id="util-template", name="Template", description="Render text template with variables", category=NodeCategory.UTILITY, icon="file-text", inputs=[NodeInput("template", "string"), NodeInput("variables", "json")], outputs=[NodeOutput("rendered", "string")]),

        # ═══════════════════ PRODUCTIVITY (8 nodes) ═══════════════════
        NodeDefinition(id="prod-notion-page", name="Notion Page", description="Create/read/update Notion pages", category=NodeCategory.PRODUCTIVITY, icon="book", inputs=[NodeInput("operation", "string"), NodeInput("page_id", "string", required=False), NodeInput("content", "json", required=False)], outputs=[NodeOutput("page", "json")], credentials=["notion"]),
        NodeDefinition(id="prod-google-sheets", name="Google Sheets", description="Read/write Google Sheets", category=NodeCategory.PRODUCTIVITY, icon="table", inputs=[NodeInput("spreadsheet_id", "string"), NodeInput("range", "string"), NodeInput("operation", "string")], outputs=[NodeOutput("data", "json")], credentials=["google"]),
        NodeDefinition(id="prod-google-calendar", name="Google Calendar", description="Manage Google Calendar events", category=NodeCategory.PRODUCTIVITY, icon="calendar", inputs=[NodeInput("operation", "string"), NodeInput("event", "json", required=False)], outputs=[NodeOutput("events", "json")], credentials=["google"]),
        NodeDefinition(id="prod-google-drive", name="Google Drive", description="Upload/download/search Google Drive files", category=NodeCategory.PRODUCTIVITY, icon="hard-drive", inputs=[NodeInput("operation", "string"), NodeInput("file_id", "string", required=False)], outputs=[NodeOutput("result", "json")], credentials=["google"]),
        NodeDefinition(id="prod-todoist", name="Todoist", description="Manage Todoist tasks", category=NodeCategory.PRODUCTIVITY, icon="check-square", inputs=[NodeInput("operation", "string"), NodeInput("task", "json", required=False)], outputs=[NodeOutput("tasks", "json")], credentials=["todoist"]),
        NodeDefinition(id="prod-trello", name="Trello", description="Manage Trello cards and boards", category=NodeCategory.PRODUCTIVITY, icon="columns", inputs=[NodeInput("operation", "string"), NodeInput("board_id", "string", required=False)], outputs=[NodeOutput("result", "json")], credentials=["trello"]),
        NodeDefinition(id="prod-jira", name="Jira", description="Manage Jira issues", category=NodeCategory.PRODUCTIVITY, icon="check-circle", inputs=[NodeInput("operation", "string"), NodeInput("issue_key", "string", required=False)], outputs=[NodeOutput("issue", "json")], credentials=["jira"]),
        NodeDefinition(id="prod-airtable", name="Airtable", description="Read/write Airtable records", category=NodeCategory.PRODUCTIVITY, icon="table", inputs=[NodeInput("base_id", "string"), NodeInput("table", "string"), NodeInput("operation", "string")], outputs=[NodeOutput("records", "json")], credentials=["airtable"]),

        # ═══════════════════ SECURITY (5 nodes) ═══════════════════
        NodeDefinition(id="sec-encrypt", name="Encrypt", description="Encrypt data with AES/RSA", category=NodeCategory.SECURITY, icon="lock", inputs=[NodeInput("data", "string"), NodeInput("algorithm", "string", default="aes-256-gcm")], outputs=[NodeOutput("encrypted", "string")], credentials=["encryption_key"]),
        NodeDefinition(id="sec-decrypt", name="Decrypt", description="Decrypt encrypted data", category=NodeCategory.SECURITY, icon="unlock", inputs=[NodeInput("data", "string")], outputs=[NodeOutput("decrypted", "string")], credentials=["encryption_key"]),
        NodeDefinition(id="sec-hash", name="Hash", description="Generate hash (SHA256/MD5/bcrypt)", category=NodeCategory.SECURITY, icon="shield", inputs=[NodeInput("data", "string"), NodeInput("algorithm", "string", default="sha256")], outputs=[NodeOutput("hash", "string")]),
        NodeDefinition(id="sec-jwt-sign", name="JWT Sign", description="Create signed JWT token", category=NodeCategory.SECURITY, icon="key", inputs=[NodeInput("payload", "json"), NodeInput("secret", "string")], outputs=[NodeOutput("token", "string")]),
        NodeDefinition(id="sec-jwt-verify", name="JWT Verify", description="Verify and decode JWT token", category=NodeCategory.SECURITY, icon="check", inputs=[NodeInput("token", "string"), NodeInput("secret", "string")], outputs=[NodeOutput("payload", "json"), NodeOutput("valid", "boolean")]),

        # ═══════════════════ FINANCE (6 nodes) ═══════════════════
        NodeDefinition(id="fin-stripe-charge", name="Stripe Charge", description="Create a Stripe payment charge", category=NodeCategory.FINANCE, icon="credit-card", inputs=[NodeInput("amount", "number"), NodeInput("currency", "string", default="usd"), NodeInput("source", "string")], outputs=[NodeOutput("charge_id", "string"), NodeOutput("status", "string")], credentials=["stripe"]),
        NodeDefinition(id="fin-stripe-customer", name="Stripe Customer", description="Manage Stripe customers", category=NodeCategory.FINANCE, icon="user", inputs=[NodeInput("operation", "string"), NodeInput("email", "string", required=False)], outputs=[NodeOutput("customer", "json")], credentials=["stripe"]),
        NodeDefinition(id="fin-paypal-payment", name="PayPal Payment", description="Create PayPal payment", category=NodeCategory.FINANCE, icon="dollar-sign", inputs=[NodeInput("amount", "number"), NodeInput("currency", "string")], outputs=[NodeOutput("payment_id", "string")], credentials=["paypal"]),
        NodeDefinition(id="fin-invoice-generate", name="Generate Invoice", description="Generate PDF invoice", category=NodeCategory.FINANCE, icon="file-text", inputs=[NodeInput("items", "json"), NodeInput("customer", "json")], outputs=[NodeOutput("pdf_url", "string"), NodeOutput("total", "number")]),
        NodeDefinition(id="fin-currency-convert", name="Currency Convert", description="Convert between currencies", category=NodeCategory.FINANCE, icon="refresh-cw", inputs=[NodeInput("amount", "number"), NodeInput("from", "string"), NodeInput("to", "string")], outputs=[NodeOutput("converted", "number"), NodeOutput("rate", "number")]),
        NodeDefinition(id="fin-expense-track", name="Expense Tracker", description="Record and categorize expenses", category=NodeCategory.FINANCE, icon="trending-down", inputs=[NodeInput("amount", "number"), NodeInput("category", "string"), NodeInput("description", "string")], outputs=[NodeOutput("expense_id", "string")]),

        # ═══════════════════ SEARCH (5 nodes) ═══════════════════
        NodeDefinition(id="search-google", name="Google Search", description="Search Google and return results", category=NodeCategory.SEARCH, icon="search", inputs=[NodeInput("query", "string"), NodeInput("num_results", "number", default=10)], outputs=[NodeOutput("results", "json")], credentials=["google_search"]),
        NodeDefinition(id="search-bing", name="Bing Search", description="Search Bing web/images/news", category=NodeCategory.SEARCH, icon="search", inputs=[NodeInput("query", "string"), NodeInput("type", "string", default="web")], outputs=[NodeOutput("results", "json")], credentials=["bing"]),
        NodeDefinition(id="search-wikipedia", name="Wikipedia Search", description="Search and fetch Wikipedia articles", category=NodeCategory.SEARCH, icon="book-open", inputs=[NodeInput("query", "string")], outputs=[NodeOutput("title", "string"), NodeOutput("content", "string"), NodeOutput("url", "string")]),
        NodeDefinition(id="search-arxiv", name="ArXiv Search", description="Search academic papers on ArXiv", category=NodeCategory.SEARCH, icon="book", inputs=[NodeInput("query", "string"), NodeInput("max_results", "number", default=5)], outputs=[NodeOutput("papers", "json")]),
        NodeDefinition(id="search-serper", name="Serper Search", description="Fast search via Serper.dev API", category=NodeCategory.SEARCH, icon="search", inputs=[NodeInput("query", "string")], outputs=[NodeOutput("results", "json")], credentials=["serper"]),

        # ═══════════════════ SOCIAL (6 nodes) ═══════════════════
        NodeDefinition(id="social-twitter-post", name="Twitter Post", description="Post to Twitter/X", category=NodeCategory.SOCIAL, icon="twitter", inputs=[NodeInput("text", "string")], outputs=[NodeOutput("tweet_id", "string")], credentials=["twitter"]),
        NodeDefinition(id="social-twitter-search", name="Twitter Search", description="Search tweets on Twitter/X", category=NodeCategory.SOCIAL, icon="search", inputs=[NodeInput("query", "string")], outputs=[NodeOutput("tweets", "json")], credentials=["twitter"]),
        NodeDefinition(id="social-linkedin-post", name="LinkedIn Post", description="Post to LinkedIn", category=NodeCategory.SOCIAL, icon="linkedin", inputs=[NodeInput("text", "string")], outputs=[NodeOutput("post_id", "string")], credentials=["linkedin"]),
        NodeDefinition(id="social-github-issue", name="GitHub Issue", description="Create/manage GitHub issues", category=NodeCategory.SOCIAL, icon="github", inputs=[NodeInput("repo", "string"), NodeInput("title", "string"), NodeInput("body", "string")], outputs=[NodeOutput("issue_number", "number")], credentials=["github"]),
        NodeDefinition(id="social-github-pr", name="GitHub PR", description="Create/manage pull requests", category=NodeCategory.SOCIAL, icon="git-pull-request", inputs=[NodeInput("repo", "string"), NodeInput("title", "string"), NodeInput("head", "string"), NodeInput("base", "string")], outputs=[NodeOutput("pr_number", "number")], credentials=["github"]),
        NodeDefinition(id="social-reddit-post", name="Reddit Post", description="Post to Reddit subreddit", category=NodeCategory.SOCIAL, icon="message-circle", inputs=[NodeInput("subreddit", "string"), NodeInput("title", "string"), NodeInput("text", "string")], outputs=[NodeOutput("post_id", "string")], credentials=["reddit"]),

        # ═══════════════════ MONITORING (5 nodes) ═══════════════════
        NodeDefinition(id="mon-healthcheck", name="Health Check", description="Check if a URL/service is healthy", category=NodeCategory.MONITORING, icon="activity", inputs=[NodeInput("url", "string"), NodeInput("timeout_ms", "number", default=5000)], outputs=[NodeOutput("status", "number"), NodeOutput("latency_ms", "number"), NodeOutput("healthy", "boolean")]),
        NodeDefinition(id="mon-uptime", name="Uptime Monitor", description="Monitor uptime and alert on downtime", category=NodeCategory.MONITORING, icon="monitor", inputs=[NodeInput("url", "string"), NodeInput("interval_seconds", "number", default=60)], outputs=[NodeOutput("up", "boolean"), NodeOutput("response_time", "number")]),
        NodeDefinition(id="mon-log-query", name="Log Query", description="Search application logs", category=NodeCategory.MONITORING, icon="file-text", inputs=[NodeInput("query", "string"), NodeInput("timerange", "string", default="1h")], outputs=[NodeOutput("entries", "json")]),
        NodeDefinition(id="mon-metric-push", name="Push Metric", description="Push custom metric to monitoring system", category=NodeCategory.MONITORING, icon="bar-chart", inputs=[NodeInput("name", "string"), NodeInput("value", "number"), NodeInput("tags", "json", required=False)], outputs=[NodeOutput("accepted", "boolean")]),
        NodeDefinition(id="mon-alert-send", name="Send Alert", description="Send alert to PagerDuty/OpsGenie/custom", category=NodeCategory.MONITORING, icon="alert-circle", inputs=[NodeInput("title", "string"), NodeInput("severity", "string"), NodeInput("details", "string")], outputs=[NodeOutput("alert_id", "string")]),

        # ═══════════════════ MEDIA (5 nodes) ═══════════════════
        NodeDefinition(id="media-image-resize", name="Image Resize", description="Resize/crop/convert images", category=NodeCategory.MEDIA, icon="image", inputs=[NodeInput("url", "string"), NodeInput("width", "number"), NodeInput("height", "number")], outputs=[NodeOutput("output_url", "string")]),
        NodeDefinition(id="media-image-generate", name="Image Generate", description="Generate image with AI (DALL-E/Stable Diffusion)", category=NodeCategory.MEDIA, icon="image", inputs=[NodeInput("prompt", "string"), NodeInput("size", "string", default="1024x1024")], outputs=[NodeOutput("image_url", "string")], credentials=["image_api"]),
        NodeDefinition(id="media-video-transcribe", name="Video Transcribe", description="Transcribe video audio to text", category=NodeCategory.MEDIA, icon="video", inputs=[NodeInput("video_url", "string")], outputs=[NodeOutput("transcript", "string")], credentials=["speech_api_key"]),
        NodeDefinition(id="media-audio-process", name="Audio Process", description="Process audio (trim, convert, combine)", category=NodeCategory.MEDIA, icon="music", inputs=[NodeInput("url", "string"), NodeInput("operation", "string")], outputs=[NodeOutput("output_url", "string")]),
        NodeDefinition(id="media-qr-generate", name="QR Code Generate", description="Generate QR code from data", category=NodeCategory.MEDIA, icon="maximize", inputs=[NodeInput("data", "string"), NodeInput("size", "number", default=256)], outputs=[NodeOutput("image_url", "string")]),

        # ═══════════════════ CRM (4 nodes) ═══════════════════
        NodeDefinition(id="crm-hubspot", name="HubSpot", description="Manage HubSpot contacts/deals", category=NodeCategory.CRM, icon="users", inputs=[NodeInput("operation", "string"), NodeInput("data", "json")], outputs=[NodeOutput("result", "json")], credentials=["hubspot"]),
        NodeDefinition(id="crm-salesforce", name="Salesforce", description="Manage Salesforce records", category=NodeCategory.CRM, icon="cloud", inputs=[NodeInput("object", "string"), NodeInput("operation", "string"), NodeInput("data", "json", required=False)], outputs=[NodeOutput("result", "json")], credentials=["salesforce"]),
        NodeDefinition(id="crm-pipedrive", name="Pipedrive", description="Manage Pipedrive deals/contacts", category=NodeCategory.CRM, icon="target", inputs=[NodeInput("operation", "string"), NodeInput("data", "json")], outputs=[NodeOutput("result", "json")], credentials=["pipedrive"]),
        NodeDefinition(id="crm-intercom", name="Intercom", description="Manage Intercom conversations", category=NodeCategory.CRM, icon="message-circle", inputs=[NodeInput("operation", "string"), NodeInput("data", "json")], outputs=[NodeOutput("result", "json")], credentials=["intercom"]),

        # ═══════════════════ ANALYTICS (4 nodes) ═══════════════════
        NodeDefinition(id="analytics-ga4", name="Google Analytics", description="Query Google Analytics data", category=NodeCategory.ANALYTICS, icon="bar-chart-2", inputs=[NodeInput("property_id", "string"), NodeInput("metrics", "json"), NodeInput("date_range", "string")], outputs=[NodeOutput("data", "json")], credentials=["google"]),
        NodeDefinition(id="analytics-mixpanel", name="Mixpanel", description="Track/query Mixpanel events", category=NodeCategory.ANALYTICS, icon="pie-chart", inputs=[NodeInput("operation", "string"), NodeInput("event", "string", required=False)], outputs=[NodeOutput("result", "json")], credentials=["mixpanel"]),
        NodeDefinition(id="analytics-posthog", name="PostHog", description="Track/query PostHog events", category=NodeCategory.ANALYTICS, icon="bar-chart", inputs=[NodeInput("operation", "string"), NodeInput("event", "json", required=False)], outputs=[NodeOutput("result", "json")], credentials=["posthog"]),
        NodeDefinition(id="analytics-plausible", name="Plausible", description="Query Plausible analytics", category=NodeCategory.ANALYTICS, icon="trending-up", inputs=[NodeInput("site_id", "string"), NodeInput("period", "string")], outputs=[NodeOutput("visitors", "number"), NodeOutput("pageviews", "number")], credentials=["plausible"]),

        # ═══════════════════ STORAGE (4 nodes) ═══════════════════
        NodeDefinition(id="storage-minio", name="MinIO", description="S3-compatible object storage", category=NodeCategory.STORAGE, icon="hard-drive", inputs=[NodeInput("bucket", "string"), NodeInput("operation", "string"), NodeInput("key", "string", required=False)], outputs=[NodeOutput("result", "json")], credentials=["minio"]),
        NodeDefinition(id="storage-ftp", name="FTP", description="Upload/download via FTP/SFTP", category=NodeCategory.STORAGE, icon="upload", inputs=[NodeInput("host", "string"), NodeInput("operation", "string"), NodeInput("path", "string")], outputs=[NodeOutput("result", "json")], credentials=["ftp"]),
        NodeDefinition(id="storage-dropbox", name="Dropbox", description="Manage Dropbox files", category=NodeCategory.STORAGE, icon="box", inputs=[NodeInput("operation", "string"), NodeInput("path", "string")], outputs=[NodeOutput("result", "json")], credentials=["dropbox"]),
        NodeDefinition(id="storage-onedrive", name="OneDrive", description="Manage OneDrive files", category=NodeCategory.STORAGE, icon="hard-drive", inputs=[NodeInput("operation", "string"), NodeInput("path", "string")], outputs=[NodeOutput("result", "json")], credentials=["microsoft365"]),

        # ═══════════════════ IOT (3 nodes) ═══════════════════
        NodeDefinition(id="iot-mqtt-publish", name="MQTT Publish", description="Publish message to MQTT topic", category=NodeCategory.IOT, icon="radio", inputs=[NodeInput("broker", "string"), NodeInput("topic", "string"), NodeInput("message", "string")], outputs=[NodeOutput("published", "boolean")], credentials=["mqtt"]),
        NodeDefinition(id="iot-mqtt-subscribe", name="MQTT Subscribe", description="Subscribe to MQTT topic", category=NodeCategory.IOT, icon="radio", inputs=[NodeInput("broker", "string"), NodeInput("topic", "string")], outputs=[NodeOutput("message", "string")], credentials=["mqtt"]),
        NodeDefinition(id="iot-home-assistant", name="Home Assistant", description="Control Home Assistant devices", category=NodeCategory.IOT, icon="home", inputs=[NodeInput("entity_id", "string"), NodeInput("action", "string")], outputs=[NodeOutput("state", "json")], credentials=["home_assistant"]),

        # ═══════════════════ VOICE (3 nodes) ═══════════════════
        NodeDefinition(id="voice-call-twilio", name="Twilio Call", description="Make a phone call via Twilio", category=NodeCategory.VOICE, icon="phone", inputs=[NodeInput("to", "string"), NodeInput("message", "string")], outputs=[NodeOutput("call_sid", "string")], credentials=["twilio"]),
        NodeDefinition(id="voice-record", name="Voice Record", description="Record audio from microphone/call", category=NodeCategory.VOICE, icon="mic", inputs=[NodeInput("duration_seconds", "number", default=30)], outputs=[NodeOutput("audio_url", "string")]),
        NodeDefinition(id="voice-ivr", name="IVR Menu", description="Interactive voice response menu", category=NodeCategory.VOICE, icon="phone", inputs=[NodeInput("prompt", "string"), NodeInput("options", "json")], outputs=[NodeOutput("selection", "string")]),

        # ═══════════════════ ECOMMERCE (4 nodes) ═══════════════════
        NodeDefinition(id="ecom-shopify", name="Shopify", description="Manage Shopify products/orders", category=NodeCategory.ECOMMERCE, icon="shopping-bag", inputs=[NodeInput("operation", "string"), NodeInput("resource", "string")], outputs=[NodeOutput("result", "json")], credentials=["shopify"]),
        NodeDefinition(id="ecom-woocommerce", name="WooCommerce", description="Manage WooCommerce store", category=NodeCategory.ECOMMERCE, icon="shopping-cart", inputs=[NodeInput("operation", "string"), NodeInput("resource", "string")], outputs=[NodeOutput("result", "json")], credentials=["woocommerce"]),
        NodeDefinition(id="ecom-inventory", name="Inventory Check", description="Check product inventory levels", category=NodeCategory.ECOMMERCE, icon="package", inputs=[NodeInput("product_id", "string")], outputs=[NodeOutput("quantity", "number"), NodeOutput("in_stock", "boolean")]),
        NodeDefinition(id="ecom-order-track", name="Order Tracking", description="Track shipment/order status", category=NodeCategory.ECOMMERCE, icon="truck", inputs=[NodeInput("tracking_number", "string"), NodeInput("carrier", "string")], outputs=[NodeOutput("status", "string"), NodeOutput("location", "string")]),

        # ═══════════════════ CUSTOM (2 nodes) ═══════════════════
        NodeDefinition(id="custom-code-python", name="Python Code", description="Execute custom Python code", category=NodeCategory.CUSTOM, icon="code", inputs=[NodeInput("code", "string"), NodeInput("input_data", "json", required=False)], outputs=[NodeOutput("result", "json")]),
        NodeDefinition(id="custom-code-javascript", name="JavaScript Code", description="Execute custom JavaScript code", category=NodeCategory.CUSTOM, icon="code", inputs=[NodeInput("code", "string"), NodeInput("input_data", "json", required=False)], outputs=[NodeOutput("result", "json")]),
    ]
